server {
    listen 80;
    server_name localhost;

    root /var/www;
    index index.php index.html;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ =404;

        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        expires off;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;  # контейнер "app" з PHP-FPM
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
